branches:
  only: master
notifications:
  email: false
  irc: 
    channels: "irc.freenode.org#travisstaging"
    template: "(STAGING) %{repository_url} (%{commit}) %{build_url} : %{message}"
  webhooks: 
    urls: http://www.postbin.org/1cig81y
    # on_start: always